### ISSUE TITLE
Setting options on the SendGrid object

### ISSUE THREAD

**Issue by pdesmarais** [tystr/TystrSendgridBundle#1]
Hi there, 

The SendGrid docs say that we can specify options on the SendGrid object with an array of options as the third argument to the __construct(). See https://github.com/sendgrid/sendgrid-php/blob/master/README.md#options

How could that be done using your service?

Thanks!

**Comment by hackzilla** [comment]
I'd override the service definition, so you could pass in your own options.

```
        <service id="tystr_sendgrid.sendgrid" class="%tystr_sendgrid.sendgrid.class%">
            <argument>%tystr_sendgrid.username%</argument>
            <argument>%tystr_sendgrid.password%</argument>
        </service>
```

**Comment by hackzilla** [comment]
in services.yml

```yaml
    tystr_sendgrid.sendgrid:
        class: '%tystr_sendgrid.sendgrid.class%'
        arguments:
            - '%tystr_sendgrid.username%'
            - '%tystr_sendgrid.password%'
            -
                enable_guzzle_exceptions: false
                turn_off_ssl_verification: false
                raise_exceptions: false

```
